services:
  - type: web
    name: health-mood
    env: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/*.jar
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: cloud
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m -XX:+UseContainerSupport
    healthCheckPath: /actuator/health

