spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
      
   sql:
    init:
      mode: always   # Usar solo nuestros scripts SQL
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
      continue-on-error: false     format_sql: false
  

app:
  security:
    cors:
      dev: false
